DEPLOY_KEY = """-----BEGIN OPENSSH
  PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAA
  AAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACBZ6nNhHQ8yIxzEUiDq2gE6v3QwEGPI4v
  TNXKRuzc62WAAAAKCaPzGxmj8x
  sQAAAAtzc2gtZWQyNTUxOQAAACBZ6nNhHQ8yIxzEUiDq
  2gE6v3QwEGPI4vTNXKRuzc62WA
  AAAEDq+eVn11G74oSRq6BC3wQBcJe9SgI0W1yImcmsqT
  eShVnqc2EdDzIjHMRSIOraATq/
  dDAQY8ji9M1cpG7NzrZYAAAAFnNpbXVsYWNyb3MtCiAg
  dXBsb2FkZXIBAgMEBQYH
  -----END OPENSSH PRIVATE KEY-----"""
GIT_REPO_URL = "git@github.com:Juankserrano7/Simulacros_AGS.git"
GIT_DEFAULT_BRANCH = "main"
GIT_AUTHOR_NAME = "Simulacros Bot"
GIT_AUTHOR_EMAIL = "bot@aspaen.edu.co"